; HEADER_BLOCK_START
; generated by OrcaSlicer 2.3.1 on 2025-11-20 at 15:29:15
; total layer number: 3
; filament_density: 1.24
; filament_diameter: 1.75
; max_z_height: 0.60
; HEADER_BLOCK_END

; THUMBNAIL_BLOCK_START

;
; thumbnail begin 48x48 412
; iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAA+0lEQVR4Ae2WsQ7CIBRF+R0X4+I3uD
; m4ujg7uTm4EHe/wI+twabNKymFUh7cl7yTsJ/DDU2NURRFUWA5n+z/iOT76cYjKsSJUnk/BJqQuIiI
; FHnIkLXiUBFb5Js+8KWHCr9GafGqa3DKs65RS5wlooV8kRCOh1otAkXcj0gKQZRPWgNdfDHi/ZQjT8
; /I/daJirhe+jPheLAiQmblKagRr0dE3F/DRaCERG89FIGwhhPf76zJplVE1q2jrFFUnsIdwSZO4Xrg
; VeQppdZY9XkszbCGmFsPReSsASFPSY2AE6fE1oCWp/gRTR9qLsMDF3Prc7iITf8xiqIoCjM/EhqmUy
; U28M8AAAAASUVORK5CYII=
; thumbnail end
; THUMBNAIL_BLOCK_END

; THUMBNAIL_BLOCK_START

;
; thumbnail begin 300x300 2428
; iVBORw0KGgoAAAANSUhEUgAAASwAAAEsCAYAAAB5fY51AAAG40lEQVR4Ae3dMY4cRRiG4b0OCSLhDG
; QEpCTERGQEJBY5J+CwRmu80F7v7Ex1V3fVV//zSO8BPNPzqSj1iqcnAAAAAAAAAAAAAAAAAAAAAAAA
; AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4DE//vDhCWBqf//18b+MFjCt7VgZLmBKz4
; N0a6yMFjCNe0P1erQMF3C5R05VTlvAcHuHymgBl+oxVoYLOFXvoTJawCnOHCsX8kAXRy7WnbaAy1w9
; VE5bwC4jx8ppC3jILENltIB3zThWhgv4woiLdaMFNEsZqtejZbigkKRTldMWFJY0SkYLCksaI8MFRS
; WNj9GCwpJGp8doGS4ItMLF+pHhAkIkjYvRgsKSRsVwQVFJI2K0oLCk8TBcUFTli3WjBUGSRmLG0TJc
; cJGkcZh9uICTJI2B0YLCkkbAcEFRST96owWFJf3YVxotwwUNvK4wx3ABdyT9qI0WFJb0YzZcUFTSj9
; doQWFJP1qj5UKeolysZw8XlJH049Tt0TJcLC/pR6nHhguWk/QjlNGisKQfnwwXRblYN1oQIelHpv6j
; ZbiI4FSll4wWU0v6MemajBZTSvoR6foMF1NI+tFobEaLoZJ+LJojF/JczsW6jma0uETSj0Jz57TFqZ
; J+DMrJaNFV0sOvzIwWXSQ99MrPcLGLi3WNymjRJOnh1pq5kOchSQ+11s9o8aakh1i1Mlp8IenhVd0M
; V3FJD6v0nNEqKukhlba5kC/E6wpaJaO1uKSHUXoko7WopIdQas1wLSLpoZOOZLTCJT1sUq8MVxgX66
; qe0QqR9FBJZ+b1h8klPUzSVRmtySQ9PNKIjNYkkh4aaXSGaxAX69K+jNbFkh4OacZcyF/AqUrqm9E6
; SdJDICVltDpL+vKl1AzXQUlftrRCRmunpC9ZWikX8g1crEtzZLTuSPoypQo5bd2Q9CVK1TJanyV9aV
; Llyo9W0pcl6d/KDZeLdSm7MqOV9KVIut3SF/JOVdKaLTdaSR++pPaWGa2kD13SsWKHK+lDltSvuNFK
; +nAl9S/iQt7FuqRt045W0oco6bqmG62kD0/SmIYPV9KHJWl8w0Yr6UOSNFeXDZeLdUk9On20kj4MSf
; N32usPSR+CpKy6jVbSP1pSbodHK+kfK2mNdg3X9999ePrz96x/qKTsfv7p49O333x4avY8WL/+8vHT
; aBkuSWf3PFaHB+sloyXpjP747f+x6jZYTluSercdqu6D5bQlqVdvjdUpg2W0JO3t1lCdOliGS1Jr98
; bq9MEyWpLu9fpivftgPXt0sFzIS7rVo0P10iEtJy2nLUnbLh2rLaMl6dGGDdWW05ake00xVkZL0nu1
; DtXuy/U9XMhLemmqU9UtTltS7VpeVxg6VltGS6pX3FBtOW1JdYoeqy2jJa3bMkO15bQlrdeSY/XCaE
; lrFHmxvpfXH6TcygzVltOWlFfJsdoyWtL8lR+qLactad6M1RuMljRXrUN16d8BzsKFvDQ+p6oGTlvS
; mEq9rtCb0ZKuy1B14LQlnZ+x6sxoSf0zVCdq/d+MGS7pdsbqAv4TUTqWi/UBvP4gtWeoBnLakh7PWE
; 3CaEm3M1QTctqSvs5YTcxoSf/WerFe8u8AZ+FCXpVzqgrktKVqeV1hAUZLFTJUC3Ha0soZqwUZLa1W
; 61C5WA/kQl4r5FRViNOWUnOxXpjRUlKGCqctRWSs+ILR0owZKm5y2tJMGSvuMloanYt1mnn9QSMyVO
; zmtKUrM1Z0YbR0ZoaK7py2dEbGitMYLfWqdaj8HSC7uZDXkZyquJzTllrzugLDGS09kqFiGk5bei9j
; xZSMlgwVUZy2ZKyIYrTq5mKdWF5/qJWhIp7TVo2MFUsxWmtmqFiW05axgihGK7/Wi3V/B0g8F/KZOV
; VRltNWTl5XgM+M1twZKnjFactYQRSjlTtULtYpq2W4XMiPHysoz2nr+lysw0Fef7gmQwWdOG0ZK4hj
; tAwVRHHaMlYQxWjtz8U6DOJCvi1DBYM5bRkriGO0DBVEcdoyVhDFaLUPlb8DhMGqXsg7VUGoSqctry
; vAIlYfLUMFi1n1tGWsYGGrjJahgiLST1vGCopJHC0X61BcyusPhgr4ZPbTlrECvjLbaBkq4F2znLaM
; FfCQkaPVerHu7wCBT66+kHeqAg654rTldQWgq7NGy1ABp+h92jJWwKl6jFbrULlYBw5pGa7thbxTFT
; BE62nLWAHD9R4sgFM9ctoyVsBU9g4WwBC3TlvGCpjSW6PldQVgarcGC2BKL6ctYwUAAAAAAAAAAAAA
; AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAa/kHE3E9/Uf3BpwAAAAASU
; VORK5CYII=
; thumbnail end
; THUMBNAIL_BLOCK_END

; external perimeters extrusion width = 0.42mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.42mm
; top infill extrusion width = 0.42mm
; first layer extrusion width = 0.50mm

; EXECUTABLE_BLOCK_START
EXCLUDE_OBJECT_DEFINE NAME=Cube_id_0_copy_0 CENTER=0,-20 POLYGON=[[-5,-25],[5,-25],[5,-15],[-5,-15],[-5,-25]]
M73 P0 R0
M106 S0
M106 P2 S0
;TYPE:Custom
SET_PRINT_STATS_INFO TOTAL_LAYER=3 CURRENT_LAYER=0

START_PRINT EXTRUDER_TEMP=220 BED_TEMP=55 Chamber=0 PRINT_MIN=-7,-27 PRINT_MAX=7,-13 FORCE_LEVELING=true
G90
G21
M83 ; use relative distances for extrusion
; filament start gcode
;right_extruder_material: PLA
SET_PRESSURE_ADVANCE ADVANCE=0.025; Override pressure advance value
M106 S0
M106 P2 S0
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;0.2
G1 E-.8 F2100
TIMELAPSE_TAKE_FRAME
;AFTER_LAYER_CHANGE
;0.2
SET_PRINT_STATS_INFO CURRENT_LAYER=1
M117 Layer 1/3 : Flashforge Generic PLA
;_SET_FAN_SPEED_CHANGING_LAYER
SET_VELOCITY_LIMIT ACCEL=500
; printing object Cube id:0 copy 0
EXCLUDE_OBJECT_START NAME=Cube_id_0_copy_0
G1 X4.1 Y-15.9 F30000
G1 Z.6
M73 P1 R0
G1 Z.2
G1 E.8 F2100
M73 P2 R0
;TYPE:Inner wall
;WIDTH:0.5
G1 F2101
G1 X-4.1 Y-15.9 E.30542
G1 X-4.1 Y-24.1 E.30542
M73 P3 R0
G1 X4.1 Y-24.1 E.30542
M73 P4 R0
G1 X4.1 Y-15.94 E.30393
M73 P5 R0
G1 X4.6 Y-15.4 F30000
M73 P7 R0
;TYPE:Outer wall
G1 F2101
G1 X-4.6 Y-15.4 E.34267
G1 X-4.6 Y-24.6 E.34267
M73 P8 R0
G1 X4.6 Y-24.6 E.34267
M73 P10 R0
G1 X4.6 Y-15.44 E.34118
M73 P11 R0
G1 E-.8 F2100
M73 P12 R0
;WIPE_START
G1 F3000
M73 P13 R0
G1 X2.6 Y-15.431
;WIPE_END
G1 X2.968 Y-23.055 Z.6 F30000
G1 X3.012 Y-23.963 Z.6
M73 P14 R0
G1 Z.2
G1 E.8 F2100
;TYPE:Bottom surface
;WIDTH:0.512642
G1 F2101
G1 X3.757 Y-23.218 E.04033
G1 X3.757 Y-22.553 E.02543
M73 P15 R0
G1 X2.553 Y-23.757 E.06516
G1 X1.889 Y-23.757 E.02543
G1 X3.757 Y-21.889 E.10112
M73 P16 R0
G1 X3.757 Y-21.225 E.02543
G1 X1.225 Y-23.757 E.13708
G1 X.561 Y-23.757 E.02543
M73 P17 R0
G1 X3.757 Y-20.561 E.17303
G1 X3.757 Y-19.896 E.02543
M73 P18 R0
G1 X-.104 Y-23.757 E.20899
G1 X-.768 Y-23.757 E.02543
M73 P19 R0
G1 X3.757 Y-19.232 E.24495
G1 X3.757 Y-18.568 E.02543
M73 P20 R0
G1 X-1.432 Y-23.757 E.28091
G1 X-2.097 Y-23.757 E.02543
M73 P21 R0
G1 X3.757 Y-17.903 E.31687
G1 X3.757 Y-17.239 E.02543
M73 P23 R0
G1 X-2.761 Y-23.757 E.35283
G1 X-3.425 Y-23.757 E.02543
M73 P24 R0
G1 X3.757 Y-16.575 E.38878
G1 X3.757 Y-16.243 E.01271
M73 P26 R0
G1 X3.425 Y-16.243 E.01272
G1 X-3.757 Y-23.425 E.38878
G1 X-3.757 Y-22.761 E.02543
M73 P27 R0
G1 X2.761 Y-16.243 E.35282
M73 P28 R0
G1 X2.096 Y-16.243 E.02543
M73 P29 R0
G1 X-3.757 Y-22.096 E.31686
G1 X-3.757 Y-21.432 E.02543
M73 P30 R0
G1 X1.432 Y-16.243 E.2809
M73 P31 R0
G1 X.768 Y-16.243 E.02543
M73 P32 R0
G1 X-3.757 Y-20.768 E.24494
G1 X-3.757 Y-20.104 E.02543
M73 P33 R0
G1 X.104 Y-16.243 E.20899
G1 X-.561 Y-16.243 E.02543
M73 P34 R0
G1 X-3.757 Y-19.439 E.17303
G1 X-3.757 Y-18.775 E.02543
M73 P35 R0
G1 X-1.225 Y-16.243 E.13707
G1 X-1.889 Y-16.243 E.02543
M73 P36 R0
G1 X-3.757 Y-18.111 E.10111
G1 X-3.757 Y-17.446 E.02543
G1 X-2.554 Y-16.243 E.06515
G1 X-3.218 Y-16.243 E.02543
M73 P37 R0
G1 X-3.963 Y-16.988 E.04033
; stop printing object Cube id:0 copy 0
M106 S255
M106 P2 S255
;LAYER_CHANGE
;Z:0.4
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;0.4
G1 E-.8 F2100
;WIPE_START
G1 F4800
G1 X-3.218 Y-16.243
G1 X-2.554 Y-16.243
M73 P38 R0
G1 X-2.753 Y-16.442
;WIPE_END
EXCLUDE_OBJECT_END NAME=Cube_id_0_copy_0
TIMELAPSE_TAKE_FRAME
;AFTER_LAYER_CHANGE
;0.4
SET_PRINT_STATS_INFO CURRENT_LAYER=2
M117 Layer 2/3 : Flashforge Generic PLA
;_SET_FAN_SPEED_CHANGING_LAYER
SET_VELOCITY_LIMIT ACCEL=10000
M140 S50 ; set bed temperature
; printing object Cube id:0 copy 0
EXCLUDE_OBJECT_START NAME=Cube_id_0_copy_0
G17
G3 Z.8 I-.136 J1.209 P1  F30000
G1 X4.355 Y-15.645 Z.8
G1 Z.4
M73 P39 R0
G1 E.8 F2100
SET_VELOCITY_LIMIT ACCEL=5000
;TYPE:Inner wall
;WIDTH:0.45
G1 F2734
G1 X-4.355 Y-15.645 E.28893
G1 X-4.355 Y-24.355 E.28893
M73 P40 R0
G1 X4.355 Y-24.355 E.28893
M73 P41 R0
G1 X4.355 Y-15.685 E.2876
M73 P42 R0
SET_VELOCITY_LIMIT ACCEL=10000
G1 X4.79 Y-15.21 F30000
SET_VELOCITY_LIMIT ACCEL=5000
;TYPE:Outer wall
;WIDTH:0.42
G1 F2734
M73 P43 R0
G1 X-4.79 Y-15.21 E.29437
G1 X-4.79 Y-24.79 E.29437
M73 P44 R0
G1 X4.79 Y-24.79 E.29437
G1 X4.79 Y-15.25 E.29314
M73 P45 R0
SET_VELOCITY_LIMIT ACCEL=10000
G1 E-.8 F2100
M73 P46 R0
;WIPE_START
G1 F12000
M73 P47 R0
G1 X2.79 Y-15.242
;WIPE_END
G1 X2.988 Y-16.112 Z.8 F30000
G1 Z.4
G1 E.8 F2100
SET_VELOCITY_LIMIT ACCEL=7000
;TYPE:Internal solid infill
;WIDTH:0.570047
G1 F2734
G1 X3.888 Y-16.112 E.03865
G1 X3.888 Y-17.012 E.03865
G1 X3.016 Y-16.14 E.05295
SET_VELOCITY_LIMIT ACCEL=10000
G1 X1.959 Y-15.671 F30000
M73 P48 R0
SET_VELOCITY_LIMIT ACCEL=7000
;WIDTH:0.422792
G1 F2734
G1 X4.159 Y-17.871 E.0963
G1 X4.159 Y-18.408 E.01663
G1 X1.592 Y-15.841 E.11239
G1 X1.054 Y-15.841 E.01663
G1 X4.159 Y-18.946 E.1359
M73 P49 R0
G1 X4.159 Y-19.483 E.01663
G1 X.517 Y-15.841 E.15942
G1 X-.02 Y-15.841 E.01663
M73 P50 R0
G1 X4.159 Y-20.02 E.18294
G1 X4.159 Y-20.557 E.01663
G1 X-.557 Y-15.841 E.20646
G1 X-1.094 Y-15.841 E.01663
M73 P51 R0
G1 X4.159 Y-21.094 E.22998
G1 X4.159 Y-21.632 E.01663
M73 P52 R0
G1 X-1.632 Y-15.841 E.25349
G1 X-2.169 Y-15.841 E.01663
M73 P53 R0
G1 X4.159 Y-22.169 E.27701
G1 X4.159 Y-22.706 E.01663
M73 P54 R0
G1 X-2.706 Y-15.841 E.30053
G1 X-3.243 Y-15.841 E.01663
M73 P55 R0
G1 X4.159 Y-23.243 E.32405
G1 X4.159 Y-23.781 E.01663
M73 P56 R0
G1 X-3.781 Y-15.841 E.34756
G1 X-4.159 Y-15.841 E.01171
M73 P57 R0
G1 X-4.159 Y-16 E.00492
G1 X4 Y-24.159 E.35718
G1 X3.463 Y-24.159 E.01663
M73 P58 R0
G1 X-4.159 Y-16.537 E.33366
G1 X-4.159 Y-17.074 E.01663
M73 P59 R0
G1 X2.926 Y-24.159 E.31014
G1 X2.389 Y-24.159 E.01663
M73 P60 R0
G1 X-4.159 Y-17.611 E.28663
M73 P61 R0
G1 X-4.159 Y-18.149 E.01663
G1 X1.851 Y-24.159 E.26311
M73 P62 R0
G1 X1.314 Y-24.159 E.01663
G1 X-4.159 Y-18.686 E.23959
G1 X-4.159 Y-19.223 E.01663
M73 P63 R0
G1 X.777 Y-24.159 E.21607
G1 X.24 Y-24.159 E.01663
M73 P64 R0
G1 X-4.159 Y-19.76 E.19256
G1 X-4.159 Y-20.298 E.01663
M73 P65 R0
G1 X-.298 Y-24.159 E.16904
G1 X-.835 Y-24.159 E.01663
G1 X-4.159 Y-20.835 E.14552
G1 X-4.159 Y-21.372 E.01663
M73 P66 R0
G1 X-1.372 Y-24.159 E.122
G1 X-1.909 Y-24.159 E.01663
G1 X-4.159 Y-21.909 E.09849
G1 X-4.159 Y-22.446 E.01663
M73 P67 R0
G1 X-2.446 Y-24.159 E.07497
G1 X-2.984 Y-24.159 E.01663
G1 X-4.159 Y-22.984 E.05145
G1 X-4.159 Y-23.521 E.01663
G1 X-3.351 Y-24.329 E.03536
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-4.011 Y-24.069 F30000
M73 P68 R0
SET_VELOCITY_LIMIT ACCEL=7000
;WIDTH:0.38292
G1 F2734
G1 X-4.075 Y-24.032 E.00204
G1 X-4.01 Y-23.997 E.00204
; stop printing object Cube id:0 copy 0
;LAYER_CHANGE
;Z:0.6
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;0.6
G1 E-.8 F2100
;WIPE_START
G1 F15000
G1 X-4.075 Y-24.032
G1 X-4.011 Y-24.069
;WIPE_END
EXCLUDE_OBJECT_END NAME=Cube_id_0_copy_0
TIMELAPSE_TAKE_FRAME
;AFTER_LAYER_CHANGE
;0.6
SET_PRINT_STATS_INFO CURRENT_LAYER=3
M117 Layer 3/3 : Flashforge Generic PLA
;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Cube id:0 copy 0
SET_VELOCITY_LIMIT ACCEL=10000
EXCLUDE_OBJECT_START NAME=Cube_id_0_copy_0
G17
G3 Z1 I-.863 J.858 P1  F30000
G1 X4.355 Y-15.645 Z1
G1 Z.6
M73 P69 R0
G1 E.8 F2100
SET_VELOCITY_LIMIT ACCEL=5000
;TYPE:Inner wall
;WIDTH:0.45
G1 F2696
G1 X-4.355 Y-15.645 E.28893
G1 X-4.355 Y-24.355 E.28893
M73 P70 R0
G1 X4.355 Y-24.355 E.28893
M73 P71 R0
G1 X4.355 Y-15.685 E.2876
M73 P72 R0
SET_VELOCITY_LIMIT ACCEL=10000
G1 X4.79 Y-15.21 F30000
SET_VELOCITY_LIMIT ACCEL=5000
;TYPE:Outer wall
;WIDTH:0.42
G1 F2696
M73 P73 R0
G1 X-4.79 Y-15.21 E.29437
G1 X-4.79 Y-24.79 E.29437
G1 X4.79 Y-24.79 E.29437
M73 P74 R0
G1 X4.79 Y-15.25 E.29314
M73 P75 R0
SET_VELOCITY_LIMIT ACCEL=10000
G1 E-.8 F2100
M73 P76 R0
;WIPE_START
G1 F12000
M73 P77 R0
G1 X2.79 Y-15.242
;WIPE_END
G1 X4.11 Y-22.759 Z1 F30000
G1 X4.231 Y-23.446 Z1
G1 Z.6
G1 E.8 F2100
SET_VELOCITY_LIMIT ACCEL=2000
;TYPE:Top surface
;WIDTH:0.43064
G1 F2696
G1 X3.446 Y-24.231 E.03507
SET_VELOCITY_LIMIT ACCEL=10000
G1 X2.897 Y-24.231 F30000
M73 P78 R0
SET_VELOCITY_LIMIT ACCEL=2000
G1 F2696
G1 X4.231 Y-22.897 E.05957
SET_VELOCITY_LIMIT ACCEL=10000
G1 X4.231 Y-22.349 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F2696
G1 X2.349 Y-24.231 E.08407
SET_VELOCITY_LIMIT ACCEL=10000
G1 X1.801 Y-24.231 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F2696
G1 X4.231 Y-21.801 E.10857
SET_VELOCITY_LIMIT ACCEL=10000
G1 X4.231 Y-21.253 F30000
M73 P79 R0
SET_VELOCITY_LIMIT ACCEL=2000
G1 F2696
G1 X1.253 Y-24.231 E.13307
SET_VELOCITY_LIMIT ACCEL=10000
G1 X.704 Y-24.231 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F2696
G1 X4.231 Y-20.704 E.15756
SET_VELOCITY_LIMIT ACCEL=10000
G1 X4.231 Y-20.156 F30000
M73 P80 R0
SET_VELOCITY_LIMIT ACCEL=2000
G1 F2696
G1 X.156 Y-24.231 E.18206
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-.392 Y-24.231 F30000
M73 P81 R0
SET_VELOCITY_LIMIT ACCEL=2000
G1 F2696
G1 X4.231 Y-19.608 E.20656
SET_VELOCITY_LIMIT ACCEL=10000
G1 X4.231 Y-19.059 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F2696
G1 X-.941 Y-24.231 E.23106
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-1.489 Y-24.231 F30000
M73 P82 R0
SET_VELOCITY_LIMIT ACCEL=2000
G1 F2696
G1 X4.231 Y-18.511 E.25556
SET_VELOCITY_LIMIT ACCEL=10000
G1 X4.231 Y-17.963 F30000
M73 P83 R0
SET_VELOCITY_LIMIT ACCEL=2000
G1 F2696
G1 X-2.037 Y-24.231 E.28006
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-2.586 Y-24.231 F30000
M73 P84 R0
SET_VELOCITY_LIMIT ACCEL=2000
G1 F2696
G1 X4.231 Y-17.414 E.30456
SET_VELOCITY_LIMIT ACCEL=10000
G1 X4.231 Y-16.866 F30000
M73 P85 R0
SET_VELOCITY_LIMIT ACCEL=2000
G1 F2696
G1 X-3.134 Y-24.231 E.32906
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-3.682 Y-24.231 F30000
M73 P86 R0
SET_VELOCITY_LIMIT ACCEL=2000
G1 F2696
G1 X4.231 Y-16.318 E.35356
SET_VELOCITY_LIMIT ACCEL=10000
G1 X4.231 Y-15.769 F30000
M73 P88 R0
SET_VELOCITY_LIMIT ACCEL=2000
G1 F2696
G1 X-4.231 Y-24.231 E.37806
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-4.231 Y-23.682 F30000
M73 P89 R0
SET_VELOCITY_LIMIT ACCEL=2000
G1 F2696
G1 X3.682 Y-15.769 E.35356
SET_VELOCITY_LIMIT ACCEL=10000
G1 X3.134 Y-15.769 F30000
M73 P90 R0
SET_VELOCITY_LIMIT ACCEL=2000
G1 F2696
G1 X-4.231 Y-23.134 E.32906
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-4.231 Y-22.586 F30000
M73 P91 R0
SET_VELOCITY_LIMIT ACCEL=2000
G1 F2696
G1 X2.586 Y-15.769 E.30456
SET_VELOCITY_LIMIT ACCEL=10000
G1 X2.037 Y-15.769 F30000
M73 P92 R0
SET_VELOCITY_LIMIT ACCEL=2000
G1 F2696
G1 X-4.231 Y-22.037 E.28006
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-4.231 Y-21.489 F30000
M73 P93 R0
SET_VELOCITY_LIMIT ACCEL=2000
G1 F2696
G1 X1.489 Y-15.769 E.25556
SET_VELOCITY_LIMIT ACCEL=10000
G1 X.941 Y-15.769 F30000
M73 P94 R0
SET_VELOCITY_LIMIT ACCEL=2000
G1 F2696
G1 X-4.231 Y-20.941 E.23106
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-4.231 Y-20.392 F30000
M73 P95 R0
SET_VELOCITY_LIMIT ACCEL=2000
G1 F2696
G1 X.392 Y-15.769 E.20656
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-.156 Y-15.769 F30000
M73 P96 R0
SET_VELOCITY_LIMIT ACCEL=2000
G1 F2696
G1 X-4.231 Y-19.844 E.18206
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-4.231 Y-19.296 F30000
M73 P97 R0
SET_VELOCITY_LIMIT ACCEL=2000
G1 F2696
G1 X-.704 Y-15.769 E.15756
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-1.253 Y-15.769 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F2696
G1 X-4.231 Y-18.747 E.13306
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-4.231 Y-18.199 F30000
M73 P98 R0
SET_VELOCITY_LIMIT ACCEL=2000
G1 F2696
G1 X-1.801 Y-15.769 E.10856
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-2.349 Y-15.769 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F2696
G1 X-4.231 Y-17.651 E.08406
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-4.231 Y-17.102 F30000
M73 P99 R0
SET_VELOCITY_LIMIT ACCEL=2000
G1 F2696
G1 X-2.898 Y-15.769 E.05956
SET_VELOCITY_LIMIT ACCEL=10000
G1 X-3.446 Y-15.769 F30000
SET_VELOCITY_LIMIT ACCEL=2000
G1 F2696
G1 X-4.231 Y-16.554 E.03506
; stop printing object Cube id:0 copy 0
G1 E-.8 F2100
;WIPE_START
G1 F12000
G1 X-3.446 Y-15.769
;WIPE_END
EXCLUDE_OBJECT_END NAME=Cube_id_0_copy_0
M106 S0
M106 P2 S0
;TYPE:Custom
; filament end gcode
END_PRINT
;total layers count = 3
M73 P100 R0
; EXECUTABLE_BLOCK_END

; filament used [mm] = 24.31
; filament used [cm3] = 0.06
; filament used [g] = 0.07
; filament cost = 0.00
; total filament used [g] = 0.07
; total filament cost = 0.00
; total layers count = 3
; estimated printing time (normal mode) = 22s
; estimated first layer printing time (normal mode) = 0.506725s

; CONFIG_BLOCK_START
; accel_to_decel_enable = 0
; accel_to_decel_factor = 50%
; activate_air_filtration = 0
; activate_chamber_temp_control = 0
; adaptive_bed_mesh_margin = 0
; adaptive_pressure_advance = 0
; adaptive_pressure_advance_bridges = 0
; adaptive_pressure_advance_model = "0,0,0\n0,0,0"
; adaptive_pressure_advance_overhangs = 0
; additional_cooling_fan_speed = 100
; align_infill_direction_to_model = 0
; alternate_extra_wall = 0
; auxiliary_fan = 1
; bbl_calib_mark_logo = 1
; bbl_use_printhost = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_exclude_area = 0x0
; bed_mesh_max = 99999,99999
; bed_mesh_min = -99999,-99999
; bed_mesh_probe_distance = 50,50
; before_layer_change_gcode = ;BEFORE_LAYER_CHANGE\n;[layer_z]
; best_object_pos = 0.5,0.4
; bottom_shell_layers = 3
; bottom_shell_thickness = 0
; bottom_solid_infill_flow_ratio = 1
; bottom_surface_density = 100%
; bottom_surface_pattern = monotonic
; bridge_acceleration = 50%
; bridge_angle = 0
; bridge_density = 100%
; bridge_flow = 1
; bridge_no_support = 0
; bridge_speed = 25
; brim_ears_detection_length = 1
; brim_ears_max_angle = 125
; brim_object_gap = 0.1
; brim_type = no_brim
; brim_width = 5
; calib_flowrate_topinfill_special_order = 0
; chamber_temperature = 0
; change_extrusion_role_gcode = 
; change_filament_gcode = 
; close_fan_the_first_x_layers = 1
; complete_print_exhaust_fan_speed = 80
; cool_plate_temp = 60
; cool_plate_temp_initial_layer = 55
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; counterbore_hole_bridging = none
; curr_bed_type = High Temp Plate
; default_acceleration = 10000
; default_bed_type = 
; default_filament_colour = ""
; default_filament_profile = "Flashforge Generic PLA"
; default_jerk = 0
; default_junction_deviation = 0
; default_print_profile = 0.20mm Standard @Flashforge AD5M Pro 0.4 Nozzle
; deretraction_speed = 35
; detect_narrow_internal_solid_infill = 1
; detect_overhang_wall = 1
; detect_thin_wall = 0
; different_settings_to_system = exclude_object;gcode_label_objects;;best_object_pos;layer_change_gcode;machine_end_gcode;machine_start_gcode;print_host;print_host_webui;thumbnails;time_lapse_gcode
; disable_m73 = 0
; dont_filter_internal_bridges = disabled
; dont_slow_down_outer_wall = 0
; draft_shield = disabled
; during_print_exhaust_fan_speed = 60
; elefant_foot_compensation = 0.15
; elefant_foot_compensation_layers = 1
; emit_machine_limits_to_gcode = 1
; enable_arc_fitting = 0
; enable_extra_bridge_layer = disabled
; enable_filament_ramming = 1
; enable_long_retraction_when_cut = 0
; enable_overhang_bridge_fan = 1
; enable_overhang_speed = 1
; enable_pressure_advance = 1
; enable_prime_tower = 0
; enable_support = 0
; enforce_support_layers = 0
; eng_plate_temp = 60
; eng_plate_temp_initial_layer = 55
; ensure_vertical_shell_thickness = ensure_all
; exclude_object = 1
; extra_loading_move = -2
; extra_perimeters_on_overhangs = 0
; extra_solid_infills = 
; extruder_clearance_height_to_lid = 150
; extruder_clearance_height_to_rod = 27
; extruder_clearance_radius = 76
; extruder_colour = #00A899
; extruder_offset = 0x0
; extrusion_rate_smoothing_external_perimeter_only = 0
; fan_cooling_layer_time = 100
; fan_kickstart = 0
; fan_max_speed = 100
; fan_min_speed = 100
; fan_speedup_overhangs = 1
; fan_speedup_time = 0
; filament_colour = #00A899
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 20
; filament_density = 1.24
; filament_diameter = 1.75
; filament_end_gcode = "; filament end gcode\n"
; filament_flow_ratio = 0.98
; filament_ids = FFG01
; filament_is_support = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 25
; filament_minimal_purge_on_wipe_tower = 15
; filament_multitool_ramming = 0
; filament_multitool_ramming_flow = 10
; filament_multitool_ramming_volume = 10
; filament_notes = ""
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = "Flashforge Generic PLA"
; filament_shrink = 100%
; filament_shrinkage_compensation_z = 100%
; filament_soluble = 0
; filament_stamping_distance = 0
; filament_stamping_loading_speed = 0
; filament_start_gcode = "; filament start gcode\n;right_extruder_material: PLA\n"
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = Generic
; filename_format = {input_filename_base}.gcode
; fill_multiline = 1
; filter_out_gap_fill = 0.5
; first_layer_print_sequence = 0
; flush_into_infill = 0
; flush_into_objects = 0
; flush_into_support = 1
; flush_multiplier = 0.8
; flush_volumes_matrix = 0
; flush_volumes_vector = 140,140
; full_fan_speed_layer = 0
; fuzzy_skin = none
; fuzzy_skin_first_layer = 0
; fuzzy_skin_mode = displacement
; fuzzy_skin_noise_type = classic
; fuzzy_skin_octaves = 4
; fuzzy_skin_persistence = 0.5
; fuzzy_skin_point_distance = 0.3
; fuzzy_skin_scale = 1
; fuzzy_skin_thickness = 0.2
; gap_fill_target = nowhere
; gap_infill_speed = 200
; gcode_add_line_number = 0
; gcode_comments = 0
; gcode_flavor = klipper
; gcode_label_objects = 1
; has_scarf_joint_seam = 0
; head_wrap_detect_zone = 
; high_current_on_filament_swap = 0
; hole_to_polyhole = 0
; hole_to_polyhole_threshold = 0.01
; hole_to_polyhole_twisted = 1
; host_type = octoprint
; hot_plate_temp = 50
; hot_plate_temp_initial_layer = 55
; idle_temperature = 0
; independent_support_layer_height = 1
; infill_anchor = 400%
; infill_anchor_max = 20
; infill_combination = 0
; infill_combination_max_layer_height = 100%
; infill_direction = 45
; infill_jerk = 9
; infill_lock_depth = 1
; infill_overhang_angle = 60
; infill_shift_step = 0.4
; infill_wall_overlap = 50%
; inherits_group = "0.20mm Standard @Flashforge AD5M Pro 0.4 Nozzle";;"Flashforge Adventurer 5M Pro 0.4 Nozzle"
; initial_layer_acceleration = 500
; initial_layer_infill_speed = 80
; initial_layer_jerk = 9
; initial_layer_line_width = 0.5
; initial_layer_min_bead_width = 85%
; initial_layer_print_height = 0.2
; initial_layer_speed = 50
; initial_layer_travel_speed = 100%
; inner_wall_acceleration = 5000
; inner_wall_jerk = 9
; inner_wall_line_width = 0.45
; inner_wall_speed = 300
; interface_shells = 0
; interlocking_beam = 0
; interlocking_beam_layer_count = 2
; interlocking_beam_width = 0.8
; interlocking_boundary_avoidance = 2
; interlocking_depth = 2
; interlocking_orientation = 22.5
; internal_bridge_angle = 0
; internal_bridge_density = 100%
; internal_bridge_fan_speed = -1
; internal_bridge_flow = 1
; internal_bridge_speed = 50
; internal_solid_infill_acceleration = 7000
; internal_solid_infill_line_width = 0.42
; internal_solid_infill_pattern = monotonic
; internal_solid_infill_speed = 250
; ironing_angle = -1
; ironing_fan_speed = -1
; ironing_flow = 15%
; ironing_inset = 0
; ironing_pattern = rectilinear
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = no ironing
; is_infill_first = 0
; lateral_lattice_angle_1 = -45
; lateral_lattice_angle_2 = 45
; layer_change_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]\nSET_PRINT_STATS_INFO CURRENT_LAYER={layer_num + 1}\nM117 Layer {layer_num+1}/[total_layer_count] : {filament_settings_id[0]}
; layer_height = 0.2
; line_width = 0.42
; long_retractions_when_cut = 0
; machine_end_gcode = END_PRINT\n;total layers count = [total_layer_count]\n
; machine_load_filament_time = 0
; machine_max_acceleration_e = 5000,5000
; machine_max_acceleration_extruding = 20000,20000
; machine_max_acceleration_retracting = 5000,5000
; machine_max_acceleration_travel = 20000,20000
; machine_max_acceleration_x = 20000,20000
; machine_max_acceleration_y = 20000,20000
; machine_max_acceleration_z = 500,500
; machine_max_jerk_e = 2.5,2.5
; machine_max_jerk_x = 9,9
; machine_max_jerk_y = 9,9
; machine_max_jerk_z = 3,3
; machine_max_junction_deviation = 0,0
; machine_max_speed_e = 30,30
; machine_max_speed_x = 600,600
; machine_max_speed_y = 600,600
; machine_max_speed_z = 20,20
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; machine_pause_gcode = M25
; machine_start_gcode = SET_PRINT_STATS_INFO TOTAL_LAYER=[total_layer_count] CURRENT_LAYER=0\n\nSTART_PRINT EXTRUDER_TEMP=[nozzle_temperature_initial_layer] BED_TEMP=[bed_temperature_initial_layer_single] Chamber=[chamber_temperature] PRINT_MIN={first_layer_print_min[0]},{first_layer_print_min[1]} PRINT_MAX={first_layer_print_max[0]},{first_layer_print_max[1]} FORCE_LEVELING=true\n
; machine_tool_change_time = 0
; machine_unload_filament_time = 0
; make_overhang_printable = 0
; make_overhang_printable_angle = 55
; make_overhang_printable_hole_size = 0
; manual_filament_change = 0
; max_bridge_length = 10
; max_layer_height = 0.28
; max_resonance_avoidance_speed = 120
; max_travel_detour_distance = 0
; max_volumetric_extrusion_rate_slope = 0
; max_volumetric_extrusion_rate_slope_segment_length = 3
; min_bead_width = 85%
; min_feature_size = 25%
; min_layer_height = 0.08
; min_length_factor = 0.5
; min_resonance_avoidance_speed = 70
; min_skirt_length = 0
; min_width_top_surface = 300%
; minimum_sparse_infill_area = 15
; mmu_segmented_region_interlocking_depth = 0
; mmu_segmented_region_max_width = 0
; notes = 
; nozzle_diameter = 0.4
; nozzle_height = 2.5
; nozzle_hrc = 0
; nozzle_temperature = 220
; nozzle_temperature_initial_layer = 220
; nozzle_temperature_range_high = 230
; nozzle_temperature_range_low = 190
; nozzle_type = stainless_steel
; nozzle_volume = 0
; only_one_wall_first_layer = 0
; only_one_wall_top = 0
; ooze_prevention = 0
; other_layers_print_sequence = 0
; other_layers_print_sequence_nums = 0
; outer_wall_acceleration = 5000
; outer_wall_jerk = 9
; outer_wall_line_width = 0.42
; outer_wall_speed = 200
; overhang_1_4_speed = 0
; overhang_2_4_speed = 40
; overhang_3_4_speed = 20
; overhang_4_4_speed = 10
; overhang_fan_speed = 100
; overhang_fan_threshold = 50%
; overhang_reverse = 0
; overhang_reverse_internal_only = 0
; overhang_reverse_threshold = 50%
; parking_pos_retraction = 92
; pellet_flow_coefficient = 0.4157
; pellet_modded_printer = 0
; post_process = 
; precise_outer_wall = 1
; precise_z_height = 0
; preferred_orientation = 0
; preheat_steps = 1
; preheat_time = 30
; pressure_advance = 0.025
; prime_tower_brim_width = 3
; prime_tower_width = 60
; prime_volume = 45
; print_compatible_printers = "Flashforge Adventurer 5M Pro 0.4 Nozzle"
; print_flow_ratio = 1
; print_order = default
; print_sequence = by layer
; print_settings_id = 0.20mm Standard @Flashforge AD5M Pro 0.4 Nozzle - Copy
; printable_area = -110x-110,110x-110,110x110,-110x110
; printable_height = 220
; printer_model = Flashforge Adventurer 5M Pro
; printer_notes = 
; printer_settings_id = Flashforge Adventurer 5M Pro 0.4 Nozzle - Pond Cottage
; printer_structure = undefine
; printer_technology = FFF
; printer_variant = 0.4
; printhost_authorization_type = key
; printhost_ssl_ignore_revoke = 0
; printing_by_object_gcode = 
; purge_in_prime_tower = 1
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 2
; raft_layers = 0
; reduce_crossing_wall = 0
; reduce_fan_stop_start_freq = 1
; reduce_infill_retraction = 1
; required_nozzle_HRC = 0
; resolution = 0.012
; resonance_avoidance = 0
; retract_before_wipe = 100%
; retract_length_toolchange = 2
; retract_lift_above = 0
; retract_lift_below = 0
; retract_lift_enforce = All Surfaces
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_when_changing_layer = 1
; retraction_distances_when_cut = 18
; retraction_length = 0.8
; retraction_minimum_travel = 1
; retraction_speed = 35
; role_based_wipe_speed = 1
; scan_first_layer = 0
; scarf_angle_threshold = 155
; scarf_joint_flow_ratio = 1
; scarf_joint_speed = 100%
; scarf_overhang_threshold = 40%
; seam_gap = 10%
; seam_position = aligned
; seam_slope_conditional = 0
; seam_slope_entire_loop = 0
; seam_slope_inner_walls = 0
; seam_slope_min_length = 20
; seam_slope_start_height = 0
; seam_slope_steps = 10
; seam_slope_type = none
; silent_mode = 0
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 0
; single_loop_draft_shield = 0
; skeleton_infill_density = 25%
; skeleton_infill_line_width = 100%
; skin_infill_density = 25%
; skin_infill_depth = 2
; skin_infill_line_width = 100%
; skirt_distance = 2
; skirt_height = 1
; skirt_loops = 0
; skirt_speed = 50
; skirt_start_angle = -135
; skirt_type = combined
; slice_closing_radius = 0.049
; slicing_mode = regular
; slow_down_for_layer_cooling = 1
; slow_down_layer_time = 6
; slow_down_layers = 1
; slow_down_min_speed = 20
; slowdown_for_curled_perimeters = 1
; small_area_infill_flow_compensation = 0
; small_area_infill_flow_compensation_model = 0,0;"\n0.2,0.4444";"\n0.4,0.6145";"\n0.6,0.7059";"\n0.8,0.7619";"\n1.5,0.8571";"\n2,0.8889";"\n3,0.9231";"\n5,0.9520";"\n10,1"
; small_perimeter_speed = 50%
; small_perimeter_threshold = 0
; solid_infill_direction = 45
; solid_infill_filament = 1
; solid_infill_rotate_template = 
; sparse_infill_acceleration = 100%
; sparse_infill_density = 15%
; sparse_infill_filament = 1
; sparse_infill_line_width = 0.45
; sparse_infill_pattern = crosshatch
; sparse_infill_rotate_template = 
; sparse_infill_speed = 270
; spiral_finishing_flow_ratio = 0
; spiral_mode = 0
; spiral_mode_max_xy_smoothing = 200%
; spiral_mode_smooth = 0
; spiral_starting_flow_ratio = 0
; staggered_inner_seams = 0
; standby_temperature_delta = -5
; start_end_points = 30x-3,54x245
; supertack_plate_temp = 35
; supertack_plate_temp_initial_layer = 35
; support_air_filtration = 1
; support_angle = 0
; support_base_pattern = rectilinear
; support_base_pattern_spacing = 2.5
; support_bottom_interface_spacing = 0.5
; support_bottom_z_distance = 0.18
; support_chamber_temp_control = 1
; support_critical_regions_only = 0
; support_expansion = 0
; support_filament = 0
; support_interface_bottom_layers = 2
; support_interface_filament = 0
; support_interface_loop_pattern = 0
; support_interface_not_for_body = 1
; support_interface_pattern = auto
; support_interface_spacing = 0.5
; support_interface_speed = 80
; support_interface_top_layers = 2
; support_ironing = 0
; support_ironing_flow = 10%
; support_ironing_pattern = rectilinear
; support_ironing_spacing = 0.1
; support_line_width = 0.42
; support_material_interface_fan_speed = 100
; support_multi_bed_types = 1
; support_object_first_layer_gap = 0.2
; support_object_xy_distance = 0.3
; support_on_build_plate_only = 0
; support_remove_small_overhang = 1
; support_speed = 150
; support_style = default
; support_threshold_angle = 30
; support_threshold_overlap = 50%
; support_top_z_distance = 0.18
; support_type = normal(auto)
; symmetric_infill_y_axis = 0
; temperature_vitrification = 60
; template_custom_gcode = 
; textured_cool_plate_temp = 40
; textured_cool_plate_temp_initial_layer = 40
; textured_plate_temp = 60
; textured_plate_temp_initial_layer = 55
; thick_bridges = 0
; thick_internal_bridges = 1
; thumbnails = 48x48/PNG, 300x300/PNG
; thumbnails_format = PNG
; time_cost = 0
; time_lapse_gcode = TIMELAPSE_TAKE_FRAME
; timelapse_type = 0
; top_bottom_infill_wall_overlap = 25%
; top_shell_layers = 5
; top_shell_thickness = 1
; top_solid_infill_flow_ratio = 1
; top_surface_acceleration = 2000
; top_surface_density = 100%
; top_surface_jerk = 9
; top_surface_line_width = 0.42
; top_surface_pattern = monotonicline
; top_surface_speed = 200
; travel_acceleration = 10000
; travel_jerk = 12
; travel_slope = 3
; travel_speed = 500
; travel_speed_z = 0
; tree_support_adaptive_layer_height = 1
; tree_support_angle_slow = 25
; tree_support_auto_brim = 1
; tree_support_branch_angle = 45
; tree_support_branch_angle_organic = 40
; tree_support_branch_diameter = 5
; tree_support_branch_diameter_angle = 5
; tree_support_branch_diameter_organic = 2
; tree_support_branch_distance = 5
; tree_support_branch_distance_organic = 1
; tree_support_brim_width = 3
; tree_support_tip_diameter = 0.8
; tree_support_top_rate = 30%
; tree_support_wall_count = 0
; upward_compatible_machine = 
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; wall_direction = auto
; wall_distribution_count = 1
; wall_filament = 1
; wall_generator = classic
; wall_loops = 2
; wall_sequence = inner wall/outer wall
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 1
; wipe_before_external_loop = 0
; wipe_distance = 2
; wipe_on_loops = 0
; wipe_speed = 200
; wipe_tower_bridging = 10
; wipe_tower_cone_angle = 30
; wipe_tower_extra_flow = 100%
; wipe_tower_extra_rib_length = 0
; wipe_tower_extra_spacing = 100%
; wipe_tower_filament = 0
; wipe_tower_fillet_wall = 1
; wipe_tower_max_purge_speed = 90
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rib_width = 8
; wipe_tower_rotation_angle = 0
; wipe_tower_wall_type = rectangle
; wipe_tower_x = 66.000
; wipe_tower_x = 66
; wipe_tower_y = 86.000
; wipe_tower_y = 86
; wiping_volumes_extruders = 70,70,70,70,70,70,70,70,70,70
; xy_contour_compensation = 0
; xy_hole_compensation = 0
; z_hop = 0.4
; z_hop_types = Auto Lift
; z_offset = 0
; first_layer_bed_temperature = 55
; bed_shape = -110x-110,110x-110,110x110,-110x110
; first_layer_temperature = 220
; first_layer_height = 0.200
; CONFIG_BLOCK_END


